{% set name = "pyloadprofilegenerator" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyloadprofilegenerator-{{ version }}.tar.gz
  sha256: f541c06922106e5c4a9ac59a5d16efbd9ab75bf1c0d586d052196778ab423d70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-git
    - pip
  run:
    - python >=3.6
    - setuptools
    - requests
    - dataclasses-json
    - pandas
    - numpy

test:
  imports:
    - pylpg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FZJ-IEK3-VSA/pylpg
  summary: Python Bindings for the LoadProfileGenerator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
